import {AirPods} from "../images";
import {useImage} from "../../../hooks/useImage";

const AirpodsArray = () => {


    const newImages = Array.of(
        useImage(AirPods[0]),
        useImage(AirPods[1]),
        useImage(AirPods[2]),
        useImage(AirPods[3]),
        useImage(AirPods[4]),
        useImage(AirPods[5]),
        useImage(AirPods[6]),
        useImage(AirPods[7]),
        useImage(AirPods[8]),
        useImage(AirPods[9]),
        useImage(AirPods[10]),
        useImage(AirPods[11]),
        useImage(AirPods[12]),
        useImage(AirPods[13]),
        useImage(AirPods[14]),
        useImage(AirPods[15]),
        useImage(AirPods[16]),
        useImage(AirPods[17]),
        useImage(AirPods[18]),
        useImage(AirPods[19]),
        useImage(AirPods[20]),
        useImage(AirPods[21]),
        useImage(AirPods[22]),
        useImage(AirPods[23]),
        useImage(AirPods[24]),
        useImage(AirPods[25]),
        useImage(AirPods[26]),
        useImage(AirPods[27]),
        useImage(AirPods[28]),
        useImage(AirPods[29]),
        useImage(AirPods[30]),
        useImage(AirPods[31]),
        useImage(AirPods[32]),
        useImage(AirPods[33]),
        useImage(AirPods[34]),
        useImage(AirPods[35]),
        useImage(AirPods[36]),
        useImage(AirPods[37]),
        useImage(AirPods[38]),
        useImage(AirPods[39]),
        useImage(AirPods[40]),
        useImage(AirPods[41]),
        useImage(AirPods[42]),
        useImage(AirPods[43]),
        useImage(AirPods[44]),
        useImage(AirPods[45]),
        useImage(AirPods[46]),
        useImage(AirPods[47]),
        useImage(AirPods[48]),
        useImage(AirPods[49]),
        useImage(AirPods[50]),
        useImage(AirPods[51]),
        useImage(AirPods[52]),
        useImage(AirPods[53]),
        useImage(AirPods[54]),
        useImage(AirPods[55]),
        useImage(AirPods[56]),
        useImage(AirPods[57]),
        useImage(AirPods[58]),
        useImage(AirPods[59]),
        useImage(AirPods[60]),
        useImage(AirPods[61]),
        useImage(AirPods[62]),
        useImage(AirPods[63]),
        useImage(AirPods[64]),
        useImage(AirPods[65]),
        useImage(AirPods[66]),
        useImage(AirPods[67]),
        useImage(AirPods[68]),
        useImage(AirPods[69]),
        useImage(AirPods[70]),
        useImage(AirPods[71]),
        useImage(AirPods[72]),
        useImage(AirPods[73]),
        useImage(AirPods[74]),
        useImage(AirPods[75]),
        useImage(AirPods[76]),
        useImage(AirPods[77]),
        useImage(AirPods[78]),
        useImage(AirPods[79]),
        useImage(AirPods[80]),
        useImage(AirPods[81]),
        useImage(AirPods[82]),
        useImage(AirPods[83]),
        useImage(AirPods[84]),
        useImage(AirPods[85]),
        useImage(AirPods[86]),
        useImage(AirPods[87]),
        useImage(AirPods[88]),
        useImage(AirPods[89]),
        useImage(AirPods[90]),
        useImage(AirPods[91]),
        useImage(AirPods[92]),
        useImage(AirPods[93]),
        useImage(AirPods[94]),
        useImage(AirPods[95]),
        useImage(AirPods[96]),
        useImage(AirPods[97]),
        useImage(AirPods[98]),
        useImage(AirPods[99]),
        useImage(AirPods[100]),
        useImage(AirPods[101]),
        useImage(AirPods[102]),
        useImage(AirPods[103]),
        useImage(AirPods[104]),
        useImage(AirPods[105]),
        useImage(AirPods[106]),
        useImage(AirPods[107]),
        useImage(AirPods[108]),
        useImage(AirPods[109]),
        useImage(AirPods[110]),
        useImage(AirPods[111]),
        useImage(AirPods[112]),
        useImage(AirPods[113]),
        useImage(AirPods[114]),
        useImage(AirPods[115]),
        useImage(AirPods[116]),
        useImage(AirPods[117]),
        useImage(AirPods[118]),
        useImage(AirPods[119]),
        useImage(AirPods[120]),
        useImage(AirPods[121]),
        useImage(AirPods[122]),
        useImage(AirPods[123]),
        useImage(AirPods[124]),
        useImage(AirPods[125]),
        useImage(AirPods[126]),
        useImage(AirPods[127]),
        useImage(AirPods[128]),
        useImage(AirPods[129]),
        useImage(AirPods[130]),
        useImage(AirPods[131]),
        useImage(AirPods[132]),
        useImage(AirPods[133]),
        useImage(AirPods[134]),
        useImage(AirPods[135]),
        useImage(AirPods[136]),
        useImage(AirPods[137]),
        useImage(AirPods[138]),
        useImage(AirPods[139]),
        useImage(AirPods[140]),
        useImage(AirPods[141]),
        useImage(AirPods[142]),
        useImage(AirPods[143]),
        useImage(AirPods[144]),
        useImage(AirPods[145]),
        useImage(AirPods[146]),
        useImage(AirPods[147]),
        useImage(AirPods[148]),
        useImage(AirPods[149]),
        useImage(AirPods[150]),
        useImage(AirPods[151]),
        useImage(AirPods[152]),
        useImage(AirPods[153]),
        useImage(AirPods[154]),
        useImage(AirPods[155]),
        useImage(AirPods[156]),
        useImage(AirPods[157]),
        useImage(AirPods[158]),
        useImage(AirPods[159]),
        useImage(AirPods[160]),
        useImage(AirPods[161]),
        useImage(AirPods[162]),
        useImage(AirPods[163]),
        useImage(AirPods[164]),
        useImage(AirPods[165]),
        useImage(AirPods[166]),
        useImage(AirPods[167]),
        useImage(AirPods[168]),
        useImage(AirPods[169]),
        useImage(AirPods[170]),
        useImage(AirPods[171]),
        useImage(AirPods[172]),
        useImage(AirPods[173]),
        useImage(AirPods[174]),
        useImage(AirPods[175]),
        useImage(AirPods[176]),
        useImage(AirPods[177]),
        useImage(AirPods[178]),
        useImage(AirPods[179]),
        useImage(AirPods[180]),
        useImage(AirPods[181]),
        useImage(AirPods[182]),
        useImage(AirPods[183]),
        useImage(AirPods[184]),
        useImage(AirPods[185]),
        useImage(AirPods[186]),
        useImage(AirPods[187]),
        useImage(AirPods[188]),
        useImage(AirPods[189]),
        useImage(AirPods[190]),
        useImage(AirPods[191]),
        useImage(AirPods[192]),
        useImage(AirPods[193]),
        useImage(AirPods[194]),
        useImage(AirPods[195]),
        useImage(AirPods[196]),
        useImage(AirPods[197]),
        useImage(AirPods[198]),
        useImage(AirPods[199]),
        useImage(AirPods[200]))
        // useImage(AirPods[201]),
        // useImage(AirPods[202]),
        // useImage(AirPods[203]),
        // useImage(AirPods[204]),
        // useImage(AirPods[205]),
        // useImage(AirPods[206]),
        // useImage(AirPods[207]),
        // useImage(AirPods[208]),
        // useImage(AirPods[209]),
        // useImage(AirPods[210]),
        // useImage(AirPods[211]),
        // useImage(AirPods[212]),
        // useImage(AirPods[213]),
        // useImage(AirPods[214]),
        // useImage(AirPods[215]),
        // useImage(AirPods[216]),
        // useImage(AirPods[217]),
        // useImage(AirPods[218]),
        // useImage(AirPods[219]),
        // useImage(AirPods[220]),
        // useImage(AirPods[221]),
        // useImage(AirPods[222]),
        // useImage(AirPods[223]),
        // useImage(AirPods[224]),
        // useImage(AirPods[225]),
        // useImage(AirPods[226]),
        // useImage(AirPods[227]),
        // useImage(AirPods[228]),
        // useImage(AirPods[229]),
        // useImage(AirPods[230]),
        // useImage(AirPods[231]),
        // useImage(AirPods[232]),
        // useImage(AirPods[233]),
        // useImage(AirPods[234]),
        // useImage(AirPods[235]),
        // useImage(AirPods[236]),
        // useImage(AirPods[237]),
        // useImage(AirPods[238]),
        // useImage(AirPods[239]),
        // useImage(AirPods[240]),
        // useImage(AirPods[241]),
        // useImage(AirPods[242]),
        // useImage(AirPods[243]),
        // useImage(AirPods[244]),
        // useImage(AirPods[245]),
        // useImage(AirPods[246]),
        // useImage(AirPods[247]),
        // useImage(AirPods[248]),
        // useImage(AirPods[249]),
        // useImage(AirPods[250]),
        // useImage(AirPods[251]),
        // useImage(AirPods[252]),
        // useImage(AirPods[253]),
        // useImage(AirPods[254]),
        // useImage(AirPods[255]),
        // useImage(AirPods[256]),
        // useImage(AirPods[257]),
        // useImage(AirPods[258]),
        // useImage(AirPods[259]),
        // useImage(AirPods[260]),
        // useImage(AirPods[261]),
        // useImage(AirPods[262]),
        // useImage(AirPods[263]),
        // useImage(AirPods[264]),
        // useImage(AirPods[265]),
        // useImage(AirPods[266]),
        // useImage(AirPods[267]),
        // useImage(AirPods[268]),
        // useImage(AirPods[269]),
        // useImage(AirPods[270]),
        // useImage(AirPods[271]),
        // useImage(AirPods[272]),
        // useImage(AirPods[273]),
        // useImage(AirPods[274]),
        // useImage(AirPods[275]),
        // useImage(AirPods[276]),
        // useImage(AirPods[277]),
        // useImage(AirPods[278]),
        // useImage(AirPods[279]),
        // useImage(AirPods[280]),
        // useImage(AirPods[281]),
        // useImage(AirPods[282]),
        // useImage(AirPods[283]),
        // useImage(AirPods[284]),
        // useImage(AirPods[285]),
        // useImage(AirPods[286]),
        // useImage(AirPods[287]),
        // useImage(AirPods[288]),
        // useImage(AirPods[289]),
        // useImage(AirPods[290]),
        // useImage(AirPods[291]),
        // useImage(AirPods[292]),
        // useImage(AirPods[293]),
        // useImage(AirPods[294]),
        // useImage(AirPods[295]),
        // useImage(AirPods[296]),
        // useImage(AirPods[297]),
        // useImage(AirPods[298]),
        // useImage(AirPods[299]),
        // useImage(AirPods[300]),
        // useImage(AirPods[301]),
        // useImage(AirPods[302]),
        // useImage(AirPods[303]),
        // useImage(AirPods[304]),
        // useImage(AirPods[305]),
        // useImage(AirPods[306]),
        // useImage(AirPods[307]),
        // useImage(AirPods[308]),
        // useImage(AirPods[309]),
        // useImage(AirPods[310]),
        // useImage(AirPods[311]),
        // useImage(AirPods[312]),
        // useImage(AirPods[313]),
        // useImage(AirPods[314]),
        // useImage(AirPods[315]),
        // useImage(AirPods[316]),
        // useImage(AirPods[317]),
        // useImage(AirPods[318]),
        // useImage(AirPods[319]),
        // useImage(AirPods[320]),
        // useImage(AirPods[321]),
        // useImage(AirPods[322]),
        // useImage(AirPods[323]),
        // useImage(AirPods[324]),
        // useImage(AirPods[325]),
        // useImage(AirPods[326]),
        // useImage(AirPods[327]),
        // useImage(AirPods[328]),
        // useImage(AirPods[329]),
        // useImage(AirPods[330]),
        // useImage(AirPods[331]),
        // useImage(AirPods[332]),
        // useImage(AirPods[333]),
        // useImage(AirPods[334]),
        // useImage(AirPods[335]),
        // useImage(AirPods[336]),
        // useImage(AirPods[337]),
        // useImage(AirPods[338]),
        // useImage(AirPods[339]),
        // useImage(AirPods[340]),
        // useImage(AirPods[341]),
        // useImage(AirPods[342]),
        // useImage(AirPods[343]),
        // useImage(AirPods[344]),
        // useImage(AirPods[345]),
        // useImage(AirPods[346]),
        // useImage(AirPods[347]),
        // useImage(AirPods[348]),
        // useImage(AirPods[349]),
        // useImage(AirPods[350]),
        // useImage(AirPods[351]),
        // useImage(AirPods[352]),
        // useImage(AirPods[353]),
        // useImage(AirPods[354]),
        // useImage(AirPods[355]),
        // useImage(AirPods[356]),
        // useImage(AirPods[357]),
        // useImage(AirPods[358]),
        // useImage(AirPods[359]),
        // useImage(AirPods[360]),
        // useImage(AirPods[361]),
        // useImage(AirPods[362]),
        // useImage(AirPods[363]),
        // useImage(AirPods[364]),
        // useImage(AirPods[365]),
        // useImage(AirPods[366]),
        // useImage(AirPods[367]),
        // useImage(AirPods[368]),
        // useImage(AirPods[369]),
        // useImage(AirPods[370]),
        // useImage(AirPods[371]),
        // useImage(AirPods[372]),
        // useImage(AirPods[373]),
        // useImage(AirPods[374]),
        // useImage(AirPods[375]),
        // useImage(AirPods[376]),
        // useImage(AirPods[377]),
        // useImage(AirPods[378]),
        // useImage(AirPods[379]),
        // useImage(AirPods[380]),
        // useImage(AirPods[381]),
        // useImage(AirPods[382]),
        // useImage(AirPods[383]),
        // useImage(AirPods[384]),
        // useImage(AirPods[385]),
        // useImage(AirPods[386]),
        // useImage(AirPods[387]),
        // useImage(AirPods[388]),
        // useImage(AirPods[389]),
        // useImage(AirPods[390]),
        // useImage(AirPods[391]),
        // useImage(AirPods[392]),
        // useImage(AirPods[393]),
        // useImage(AirPods[394]),
        // useImage(AirPods[395]),
        // useImage(AirPods[396]),
        // useImage(AirPods[397]),
        // useImage(AirPods[398]),
        // useImage(AirPods[399]),
        // useImage(AirPods[400]),
        // useImage(AirPods[401]),
        // useImage(AirPods[402]),
        // useImage(AirPods[403]),
        // useImage(AirPods[404]),
        // useImage(AirPods[405]),
        // useImage(AirPods[406]),
        // useImage(AirPods[407]),
        // useImage(AirPods[408]),
        // useImage(AirPods[409]),
        // useImage(AirPods[410]),
        // useImage(AirPods[411]),
        // useImage(AirPods[412]),
        // useImage(AirPods[413]),
        // useImage(AirPods[414]),
        // useImage(AirPods[415]),
        // useImage(AirPods[416]),
        // useImage(AirPods[417]),
        // useImage(AirPods[418]),
        // useImage(AirPods[419]),
        // useImage(AirPods[420]),
        // useImage(AirPods[421]),
        // useImage(AirPods[422]),
        // useImage(AirPods[423]),
        // useImage(AirPods[424]),
        // useImage(AirPods[425]),
        // useImage(AirPods[426]),
        // useImage(AirPods[427]),
        // useImage(AirPods[428]),
        // useImage(AirPods[429]),
        // useImage(AirPods[430]),
        // useImage(AirPods[431]),
        // useImage(AirPods[432]),
        // useImage(AirPods[433]),
        // useImage(AirPods[434]),
        // useImage(AirPods[435]),
        // useImage(AirPods[436]),
        // useImage(AirPods[437]),
        // useImage(AirPods[438]),
        // useImage(AirPods[439]),
        // useImage(AirPods[440]),
        // useImage(AirPods[441]),
        // useImage(AirPods[442]),
        // useImage(AirPods[443]),
        // useImage(AirPods[444]),
        // useImage(AirPods[445]),
        // useImage(AirPods[446]),
        // useImage(AirPods[447]),
        // useImage(AirPods[448]),
        // useImage(AirPods[449]),
        // useImage(AirPods[450]),
        // useImage(AirPods[451]),
        // useImage(AirPods[452]),
        // useImage(AirPods[453]),
        // useImage(AirPods[454]),
        // useImage(AirPods[455]),
        // useImage(AirPods[456]),
        // useImage(AirPods[457]),
        // useImage(AirPods[458]),
        // useImage(AirPods[459]),
        // useImage(AirPods[460]),
        // useImage(AirPods[461]),
        // useImage(AirPods[462]),
        // useImage(AirPods[463]),
        // useImage(AirPods[464]),
        // useImage(AirPods[465]),
        // useImage(AirPods[466]),
        // useImage(AirPods[467]),
        // useImage(AirPods[468]),
        // useImage(AirPods[469]),
        // useImage(AirPods[470]),
        // useImage(AirPods[471]),
        // useImage(AirPods[472]),
        // useImage(AirPods[473]),
        // useImage(AirPods[474]),
        // useImage(AirPods[475]),
        // useImage(AirPods[476]),
        // useImage(AirPods[477]),
        // useImage(AirPods[478]),
        // useImage(AirPods[479]),
        // useImage(AirPods[480]),
        // useImage(AirPods[481]),
        // useImage(AirPods[482]),
        // useImage(AirPods[483]),
        // useImage(AirPods[484]),
        // useImage(AirPods[485]),
        // useImage(AirPods[486]),
        // useImage(AirPods[487]),
        // useImage(AirPods[488]),
        // useImage(AirPods[489]),
        // useImage(AirPods[490]),
        // useImage(AirPods[491]),
        // useImage(AirPods[492]),
        // useImage(AirPods[493]),
        // useImage(AirPods[494]),
        // useImage(AirPods[495]),
        // useImage(AirPods[496]),
        // useImage(AirPods[497]),
        // useImage(AirPods[498]),
        // useImage(AirPods[499]),
        // useImage(AirPods[500]),
        // useImage(AirPods[501]),
        // useImage(AirPods[502]),
        // useImage(AirPods[503]),
        // useImage(AirPods[504]),
        // useImage(AirPods[505]),
        // useImage(AirPods[506]),
        // useImage(AirPods[507]),
        // useImage(AirPods[508]),
        // useImage(AirPods[509]),
        // useImage(AirPods[510]),
        // useImage(AirPods[511]),
        // useImage(AirPods[512]),
        // useImage(AirPods[513]),
        // useImage(AirPods[514]),
        // useImage(AirPods[515]),
        // useImage(AirPods[516]),
        // useImage(AirPods[517]),
        // useImage(AirPods[518]),
        // useImage(AirPods[519]),
        // useImage(AirPods[520]),
        // useImage(AirPods[521]),
        // useImage(AirPods[522]),
        // useImage(AirPods[523]),
        // useImage(AirPods[524]),
        // useImage(AirPods[525]),
        // useImage(AirPods[526]),
        // useImage(AirPods[527]),
        // useImage(AirPods[528]),
        // useImage(AirPods[529]),
        // useImage(AirPods[530]),
        // useImage(AirPods[531]),
        // useImage(AirPods[532]),
        // useImage(AirPods[533]),
        // useImage(AirPods[534]),
        // useImage(AirPods[535]),
        // useImage(AirPods[536]),
        // useImage(AirPods[537]),
        // useImage(AirPods[538]),
        // useImage(AirPods[539]),
        // useImage(AirPods[540]),
        // useImage(AirPods[541]),
        // useImage(AirPods[542]),
        // useImage(AirPods[543]),
        // useImage(AirPods[544]),
        // useImage(AirPods[545]),
        // useImage(AirPods[546]),
        // useImage(AirPods[547]),
        // useImage(AirPods[548]),
        // useImage(AirPods[549]),
        // useImage(AirPods[550]),
        // useImage(AirPods[551]),
        // useImage(AirPods[552]),
        // useImage(AirPods[553]),
        // useImage(AirPods[554]),
        // useImage(AirPods[555]),
        // useImage(AirPods[556]),
        // useImage(AirPods[557]),
        // useImage(AirPods[558]),
        // useImage(AirPods[559]),
        // useImage(AirPods[560]),
        // useImage(AirPods[561]),
        // useImage(AirPods[562]),
        // useImage(AirPods[563]),
        // useImage(AirPods[564]),
        // useImage(AirPods[565]),
        // useImage(AirPods[566]),
        // useImage(AirPods[567]),
        // useImage(AirPods[568]),
        // useImage(AirPods[569]),
        // useImage(AirPods[570]),
        // useImage(AirPods[571]),
        // useImage(AirPods[572]),
        // useImage(AirPods[573]),
        // useImage(AirPods[574]),
        // useImage(AirPods[575]),
        // useImage(AirPods[576]),
        // useImage(AirPods[577]),
        // useImage(AirPods[578]),
        // useImage(AirPods[579]),
        // useImage(AirPods[580]),
        // useImage(AirPods[581]),
        // useImage(AirPods[582]),
        // useImage(AirPods[583]),
        // useImage(AirPods[584]),
        // useImage(AirPods[585]),
        // useImage(AirPods[586]),
        // useImage(AirPods[587]),
        // useImage(AirPods[588]),
        // useImage(AirPods[589]),
        // useImage(AirPods[590]),
        // useImage(AirPods[591]),
        // useImage(AirPods[592]),
        // useImage(AirPods[593]),
        // useImage(AirPods[594]),
        // useImage(AirPods[595]),
        // useImage(AirPods[596]),
        // useImage(AirPods[597]),
        // useImage(AirPods[598]),
        // useImage(AirPods[599]))
    return newImages
}
export default AirpodsArray;

